module.exports = [
  'NONE',
  'WEP',
  'WPA1PSKWPA2PSK/TKIPAES',
  'WPA1PSKWPA2PSK/TKIP',
  'WPA1PSKWPA2PSK/AES',
  'WPA2PSK/TKIPAES',
  'WPA2PSK/AES',
  'WPA2PSK/TKIP',
  'WPAPSK/TKIPAES',
  'WPAPSK/AES',
  'WPAPSK/TKIP'
]